### ISSUE TITLE
Is this stable / production ready?

### ISSUE THREAD

**Issue by davidthomasparks** [agcty/web3-starter#2]
Yo!

We are currently struggling with v6 of web3-react at prysm.xyz and noticed this repo uses the new v8 version which fixes a lot of the seemingly broken things about the wallet connect connectors. I'm curious if this repo is stable to cherry-pick some things out of to use in our refactor to v8?

Thanks,
David
https://www.prysm.xyz

**Comment by agcty** [comment]
It's almost production-ready, there are some performance issues with web3-react that translate into issues with 
the useToken/useContract hooks (swr caching kind of broken) and generally make your app slower.

Here's the related issue I opened that you can track https://github.com/NoahZinsmeister/web3-react/issues/470.

I also provided a solution to the problem which you can definitely already use if you're in a hurry.

You can check out the "performance" branch of this repo and more specifically the balance page for a working solution.

**Comment by davidthomasparks** [comment]
@agcty  awesome thank you so much mate! I will take a look at the perf branch. Your code is a huge help due to the lack of concrete examples for priority connectors and stuff. 

Thanks again

**Comment by agcty** [comment]
@davidthomasparks creating a pr for that for web3-react itself, so might be supported by default very soon :)
